version: '3'
services:
  everest-ui:
    build: .
    ports:
      - "4000:8080"
    volumes:
      - ./src:/app/src
      # Allows us to remove and recreate container to get new
      # compiler/bundler/linter settings:
      - ./webpack.config.js:/app/webpack.config.js
      - ./tsconfig.json:/app/tsconfig.json
      - ./tslint.json:/app/tslint.json
      - ./.stylelintrc:/app/.stylelintrc
    restart: on-failure
