forge "https://forgeapi.puppetlabs.com"

mod "nsidc/nsidc_jenkins",
  :git => "git@bitbucket.org:/nsidc/puppet-nsidc-jenkins.git",
  :ref => "v3.0.0"

mod "nsidc/nsidc_nfs",
  :git => "git@bitbucket.org:/nsidc/puppet-nsidc-nfs.git",
  :ref => "latest"

# Module for installing packages from apt
mod 'puppetlabs/apt', "< 8.0.0"

# Module for webserver (nginx) install
mod 'nsidc/puppet-nginx',
  :git => 'https://github.com/nsidc/puppet-nginx',
  :ref => 'puppet6'

mod 'willdurand/nodejs', '2.1.1'
