version: 2

jobs:
  test:
    docker:
      - image: circleci/node:8
    working_directory: ~/everest-ui
    steps:
      - checkout
      - run:
          name: Run tests
          command: |
            npm install
            npm run lint
            npm run test

workflows:
  version: 2

  build-and-deploy:
    jobs:
      - test
      #- build:
      #    filters:
      #      tags:
      #        only: /^.*$/
      #- deploy:
      #    context: org-global
      #    requires:
      #      - build
      #      - test
      #    filters:
      #      tags:
      #        only: /^.*$/
      #      branches:
      #        only: /^master$/
