version: 2.1

setup: &setup
  working_directory: ~/data-access-tools
  docker:
    - image: node:14.17

jobs:
  test:
    <<: *setup
    steps:
      - checkout
      - run:
          name: Run tests
          command: |
            npm install
            npm run lint
            npm run test

  package-and-publish:
    <<: *setup
    steps:
      - attach_workspace:
          at: ~/data-access-tools
      - run:
          name: Build package
          command: npm run build-drupal
      - run:
          name: Publish to npmjs.org
          command: |
            echo "//registry.npmjs.org/:_authToken=${NPM_DEPLOY_TOKEN}" >> ~/.npmrc
            npm --access public publish

workflows:
  version: 2.1

  test-package-publish:
    jobs:
      - test:
          filters:
            tags:
              only: /^.*$/

    package-and-publish:
      context: org-global
      requires:
        - test
      filters:
        branches:
          ignore: /.*/
        tags:
          only: /^v[0-9]+(\.[0-9]+)*(\-[\.a-zA-Z0-9]+)?$/
