#!/bin/bash
# This script is expected to be run from the Drupal VM that is being targeted to
# for deployment via garrison.
set -e

ENVIRONMENT=$1


######################
# VERIFY ENVIRONMENT #
######################

if [ "${ENVIRONMENT}" = "production" ]; then
    EXPECTED_VM="nsidc.org.drupal.apps.int.nsidc.org"
else
    EXPECTED_VM="${ENVIRONMENT}.nsidc.org.drupal.apps.int.nsidc.org"
fi
if [ "${EXPECTED_VM}" != $(facter cname) ]; then
    echo "Error: tried to deploy to environment \"${ENVIRONMENT}\" on VM $(facter cname)"
    exit 1
fi


########################
# INSTALL DEPENDENCIES #
########################

npm ci


################
# BUILD BUNDLE #
################

# allow node to use up to 4GB of RAM
NODE_OPTIONS='--max-old-space-size=4096' npm run build-drupal


#################
# DEPLOY BUNDLE #
#################

THIS_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

FROM="$THIS_DIR/../dist/*"
TO=/share/apps/everest-ui

rm -rf $TO/*
cp -R $FROM $TO/.

echo "App deployed to $TO"


##################
# UPDATE GIT TAG #
##################

if [ -n "$ENVIRONMENT" ]; then
    git tag --force $ENVIRONMENT
    git push --force origin refs/tags/$ENVIRONMENT
fi
